### ISSUE TITLE
Give the possibility to add a custom message 

### ISSUE THREAD

**Issue by fathib** [tpierrain/NFluent#105]
When I'm using NUnit with TestCase attribute, it can be useful to me to add a description to explicit the context.

**Comment by dupdob** [comment]
I propose to add _IsCloseTo_ as an entry point.
Syntax to be:
`Check.That(0.42).IsCloseTo(0.4, 0.1); // succeed`
`Check.That(0.42).IsCloseTo(0.4, 0.01); // fails`
