### ISSUE TITLE
Provide more hints to solve any broken .ContainsExactly(...) check

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#124]
Today, a typical error message for .ContrainsExactly(...) gives:

    The checked enumerable does not contain exactly the expected value(s).
    The checked enumerable:
	    ["+5 Dexterity Vest", "Aged Brie", "Elixir of the Mongoose", "Sulfuras, Hand of Ragnaros", "Backstagex passes to a TAFKAL80ETC concert", "Conjured Mana Cake"] (6 items)
    The expected value(s):
	    ["+5 Dexterity Vest", "Aged Brie", "Elixir of the Mongoose", "Sulfuras, Hand of Ragnaros", "Backstage passes to a TAFKAL80ETC concert", "Conjured Mana Cake"] (6 items)

Here, it would be interesting to know that the issue is tight to the fifth element and to zoom on the difference (depending on the type).

**Comment by dupdob** [comment]
Issue has been fixed during error messages revamping
