### ISSUE TITLE
equals with long fail

### ISSUE THREAD

**Issue by chouteau** [tpierrain/NFluent#132]
When I check this code :

long l = 12345678;
Check.That(l).Equals(12345678);

Fail with error "The checked value is different from the expected one."

**Comment by pirrmann** [comment]
If you really use IsEqualTo, it works.
Equals does perform the object comparison of the two values, which are indeed different:
```
object l = 12345678L;
object i = 12345678;
Check.That(l.Equals(i)).IsFalse(); // it is indeed false
```

**Comment by rhwy** [comment]
once 12345678 can be int, it's the preferred type and because Equals compares objects (values+types) it can't be equal in your case. 
it's quite rare to use the Equals and if you don't really need it, the IsEqualTo is the most common and natural way to compare:
  
    long actual = 12345678;
    long expected = 12345678;
    Check.That(actual).Equals(Expected); // -> works
    Check.That(actual).IsEqualTo(12345678); // -> works too

**Comment by chouteau** [comment]
I had not seen the method IsEqualTo(), I'll use it now, thank you for the support
