### ISSUE TITLE
New Feature (maybe) : Check the InnerException details

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#133]
Hi There,

I wondered whether there is any way to check the Message of an innerException when thrown.

Consider this code :
Check.ThatCode(() => A.Raise()).Throws<ApplicationException>()._**InnerException()**_.WithMessage("Out of Range.");

Currently: **_InnerException()_** does not exist.

Such code does not help too because, it compares objects' instances:
Check.ThatCode(() => A.Raise()).Throws<ApplicationException>().WithProperty("InnerException", new Exception("Out of Range."));

Thx

**Comment by tpierrain** [comment]
Just added a first draw here:
https://github.com/tpierrain/NFluent/blob/master/NFluent.35.Tests/LambdaRelatedTests.cs#L189

The happy path works, but I have to continue and to test/implement the 'Not' version of this new DueTo<E> operator.
Meanwhile, feedbacks (about the message errors) are welcome.

**Comment by tpierrain** [comment]
FYI if you would like to play the beta testers:
https://twitter.com/nfluent/status/713693473631764481

**Comment by SilNak** [comment]
+1 beta tester !
I'll assess that over the weekend.

**Comment by SilNak** [comment]
Thank you for this beta.

This UC works fine:
```
[Test]
public void SampleDueTo_1()
{
   Check.ThatCode(() => { throw new ApplicationException("Application Exception message", new ArgumentOutOfRangeException("Args not in range")); }).Throws<ApplicationException>().WithMessage("Application Exception message");
}
```

This one not:
```
[Test]
public void SampleDueTo_2()
{
   Check.ThatCode(() => { throw new ApplicationException("Application Exception message", new ArgumentOutOfRangeException("Args not in range")); }).Throws<ApplicationException>().DueTo<ArgumentOutOfRangeException>().WithMessage("Args not in range");
}
```
**_WithMessage is missing!_**

We need the same Checks as for the top level Exception:

**Comment by SilNak** [comment]
Additional info regarding my last post:

If I use **_.And.WithMessage_**, no more chance :-(
```
[Test]
public void SampleDueTo_3()
{
   Check.ThatCode(() => { throw new ApplicationException("Application Exception message", new ArgumentOutOfRangeException("Args not in range")); }).Throws<ApplicationException>().DueTo<ArgumentOutOfRangeException>().And.WithMessage("Args not in range");
}
```
the `.And.WithMessage` refers to the top level Exception instead of the `InnerException`.

**Comment by tpierrain** [comment]
@SilNak : Thanks for your feedback. Those missing behaviours are due to the fact that I only implemented a first draft of the DueTo() operator (to basically have an idea of the error message). Let me get back to you when I'll implement the entire (and unit tested) DueTo feature (including its link with the other operators like .With...). Sorry if I made you spend time for nothing.

**Comment by SilNak** [comment]
No worries !
NFluent with its condensed asserts is a real time gain.
Don't  hesitate to ask me to test again. 

By the way, Nuget allows pre-release to be pushed on servers.
It's more convenient to test-it because manually installs are constantly updated by the 'release' one. 
So don't hesitate to push your pre-release. 

Sounds fine ?

**Comment by dupdob** [comment]
I just fixed the fluent behaviour of 'DueTo()' so that you can check the inner Exception.
