### ISSUE TITLE
Avoid the Tricky case of Check.That(false);

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#136]
Hi Folks,

As I'm becoming an nFluent fan, I'm just bothered by the following tricky case:
`Check.That(False);`
 or in real life...
`Check.That(A.IsInitialized());` <= whatever the return, the test runner does not raise here !

This is a '**by design**' behaviour, because according to conceptors, nFluent does not have an assertion to execute (a Check). I perfectly understand this but ...

... what solutions could be found whether, by mistake, the 'sleepy' developper forget the terminal assertion ?

a) A warning or compilation error such as:

```
Missing the terminal Check to 'Check.That(A.IsInitialized());', please add it to your code.`
in line ... blabla...
```

b) A Debugger.Break() instruction visible at the execution time

**_What modification does it implies in the source code to allow this ?_**

**Comment by dupdob** [comment]
Depends on #198

**Comment by dnperfors** [comment]
Is this something that should be solved inside NFluent or would a separate Roslyn analyzer be fine?

**Comment by dupdob** [comment]
I think an analyzer could do the trick, indeed.
