### ISSUE TITLE
Need for a new Check for 'short' type

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#137]
I there, 

Unlike other basic type (int, string), this code does not have proper extension, so the following does not compile:
`            short sValue = 10;
            int iValue = 9;
            Check.That(sValue).IsEqualTo<short>(iValue + 1);`

The gentle message is:

> NFluent.FluentCheckException: 
The checked value is different from the expected one.
The checked value:
	[10] of type: [short]
The expected value:
	[10] of type: [int]

The current work around would be:
`            short sValue = 10;
            int iValue = 9;
            Check.That<short>(sValue).IsEqualTo<short>(iValue + 1);`

The condensed syntax would be fine:
`            short sValue = 10;
            int iValue = 9;
            Check.That(sValue).IsEqualTo(iValue + 1);`

**Comment by dupdob** [comment]
Hello
thanks for the report. This is the expected behavior.

**Comment by dupdob** [comment]
**Closed** Moved to feature request #142
