### ISSUE TITLE
Naming consistency between .Not.IsEqualTo & .IsNotEqualTo.

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#139]
Hi there,

nFluent has the aim to be close to the speaking language, so I'm a bit confused by the two possible ways to express stuffs like this:

`Check.That("FooBar").IsNotEqualTo("BarFoo")`
     and
`Check.That("FooBar").Not.IsEqualTo("BarFoo")`

In my opinion, a non redundant way to express checks is preferable, I'm leaning towards:
`Check.That("FooBar").Not.IsEqualTo("BarFoo")`
and to deprecate :
`IsNot____` idioms

Better:
`Not `could be renamed as `IsNot`to give:
`Check.That("FooBar").IsNot.EqualTo("BarFoo")`

_I suppose the `Not ` was introduced in a second time..._

What's your opinion ?

**Comment by dupdob** [comment]
Actually both APIs were released at the same time. For my own part, I do not like _Not_ as I find it lessen the readability of the check. 
We considered having _Is_ as an isolated keyword, but it was not retained as it slowed down SDHP by forcing Is before discovering the existing checks. That being said, I am not sure the idea of having _IsNot_ has been evaluated at the time
