### ISSUE TITLE
nFluent and operators

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#140]
Hi folks,

In my attempts to kill any 'Assert'  as an Hi-Valued serial killer :-),
I stays stucked with the following...

Consider a poor implementation that I cannot derive:
```
        public sealed class Person
        {
            public String Name { get; set; }
        }
```
Well poor implementation can always be worked around, so, consider this:
```
        public class PersonEx
        {
            public String Name { get; set; }
            public String Surname { get; set; }

            public static bool operator ==(PersonEx person1, Person person2)
            {
                return person1.Name == person2.Name;
            }
            public static bool operator !=(PersonEx person1, Person person2)
            {
                return person1.Name != person2.Name;
            }
            public static bool operator ==(Person person1, PersonEx person2)
            {
                return person1.Name == person2.Name;
            }
            public static bool operator !=(Person person1, PersonEx person2)
            {
                return person1.Name != person2.Name;
            }
        }
```

Hence, my nfluent test gives:
```
        [Test]
        public void SimpleTest()
        {
            Person mySelf = new Person() { Name = "SilNak" };
            PersonEx myClone = new PersonEx() { Name = "SilNak" };

            Check.That(myClone).IsEqualTo(mySelf); **<- This fails at the execution time**
            Check.That(mySelf).IsEqualTo(myClone);  **<- This fails at the execution time**

            Check.That<PersonEx>(myClone).IsEqualTo<Person>(mySelf);  **<- This fails at the compile time**
            Check.That<Person>(mySelf).IsEqualTo<PersonEx>(myClone);  **<- This fails at the compile time**
        }
```

Variance / Covariance / Contravariance can't help there in extension 'Check' methods...

So, what is the most elegant way to address this ?

The regular assert:
`Assert.AreEqual(MySelf, MyClone);`

Does the job :-(

**Comment by dupdob** [comment]
Sorry for the late reply, been busy preparing Devoxx. I am currently reproducing those **issues** and will revert as soon as I have infos

**Comment by dupdob** [comment]
It is logical that `Check.That<PersonEx>(myClone).IsEqualTo<Person>(mySelf)` fails to compile: there is no such method. Same for the inverted one. There is no added value to specify types here.

**Comment by dupdob** [comment]
The second issue is that NFluent uses _Equals_ methods to check for equality. By default, the _== operator_ checks for same reference (i.e. same object) not for same value.
If you think we need to cover the equal operator, can you please upvote/comment the associated enhancement request #154

**Comment by SilNak** [comment]
No problem, have a good time @ Devoxx, I commented the #154 .
