### ISSUE TITLE
Issue in HasFieldsWithSameValues with base types properties

### ISSUE THREAD

**Issue by benjaminbelloyan** [tpierrain/NFluent#141]
Hello there, 

I'm new to NFluent which I think is a great assertion library! However, I'm having an issue with the call to HasFieldsWithSameValues on different values for base type properties.

Here is my usecase:

    [TestFixture]
    class SampleTest
    {
        class Base
        {
            public string BaseProperty {get;set;}
        }
        class Impl : Base
        {

            public string ImplProperty { get; set; }
        }

        [Test]
        public void Test1()
        {
            Impl impl = new Impl { BaseProperty = "Any", ImplProperty = "Any1" };

            Check.That(impl).HasFieldsWithSameValues(new { BaseProperty = "Any", ImplProperty = "Any2" });
        }

        [Test]
        public void Test2()
        {
            Impl impl = new Impl { BaseProperty = "Any1", ImplProperty = "Any" };

            Check.That(impl).HasFieldsWithSameValues(new { BaseProperty = "Any2", ImplProperty = "Any" });
        }

        [Test]
        public void Test3()
        {
            Impl impl = new Impl { BaseProperty = "Any1", ImplProperty = "Any" };
            Impl impl2 = new Impl { BaseProperty = "Any2", ImplProperty = "Any" };

            Check.That(impl).HasFieldsWithSameValues(impl2);
        }
    }

The 3 test methods should fail, but only the first one actually does. I first thought it was because the dynamic object has the property not on its base type, but even with both object of the same type, the equality on base type properties seems not to be checked. I'm using version 1.3.1

Am I missing something, or is there a bug with this scenario?

**Comment by dupdob** [comment]
Hello
thanks for a clear reporting about your issue, including code to help reproduce. A fix was in progress, but your test showed my fix was incomplete, so thank you.

**Comment by dupdob** [comment]
It turns out the method does not recurse properly along the inheritance chain.

**Comment by benjaminbelloyan** [comment]
Ok noted. Thanks for the quick answer
