### ISSUE TITLE
Only first level template is checked when using Throws or DoesNotThrow

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#143]
Hi,

In my exploration of nFluent, I noticed idioms 'Throws' or 'DoesNotThrow' ignore the inner template, this lead the following to be passing, although it should not:

```
        public class InnerFakeDetails
        {
            public InnerFakeDetails(Exception inner) { InnerException = inner; }
            public Exception InnerException { get; set; }
        }
```

In the following, the assert does not raise, although `_FaultException<ExceptionDetail>_` is different of `_FaultException<InnerFakeDetails>_`

```
        [Test]
        public void BloodyWCF_1()
        {
            Check.ThatCode(() => { throw new FaultException<ExceptionDetail>(new ExceptionDetail(new ArgumentOutOfRangeException("Args not in range"))); }).Throws<FaultException<InnerFakeDetails>>();
        }
```

**Comment by dupdob** [comment]
Hi @SilNak 
I am afraid I misread your issue the first time.
The good news is that I am not able to reproduce your issue with V2.3, indicating this problem has probably been fixed as part of the overall maintenance effort.

If this issue is relevant to you, please provide feedback
