### ISSUE TITLE
.WithMessage(...) and Localization !

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#146]
Hi Folks ! Thanks again for this brilliant library !

By exploring new features, I discovered an annoying problem.

My french Windows localizes all error message. So this test works like a charm:
```
        [Test]
        public void WithMessage_And_Locale()
        {
            Check.ThatCode(() => { throw new ArgumentNullException("MyParam"); }).Throws<ArgumentNullException>().WithMessage("La valeur ne peut pas être null.\r\nNom du paramètre: MyParam");
        }
```

**_When this innocent test is rolling to my SF (which is English(US)). The test fails because the error message is localized in English._**

May we can pass the locale as a parameter of the **`WithMessage(..., _myCulture_)`** to fix the message text as invariant ?

**Comment by SilNak** [comment]
In addition to my preceding post, here how .Net is localizing the message (notice _**Environment.GetResourceString**_):

```
public override string Message
{
    [__DynamicallyInvokable]
    get
    {
        string message = base.Message;
        if(!string.IsNullOrEmpty(this.m_paramName))
        {
            string resourceString = Environment.GetResourceString("Arg_ParamName_Name", new object[]
            {
                        this.m_paramName
            });
            return message + Environment.NewLine + resourceString;
        }
        return message;
    }
}
```
and deeper in detail...

```
// System.Environment
[SecuritySafeCritical]
internal static string GetResourceString(string key, params object[] values)
{
    string resourceString = Environment.GetResourceString(key);
    return string.Format(CultureInfo.CurrentCulture, resourceString, values);
}
```

**Comment by dupdob** [comment]
Hi SilNak,
One quick fix for that issue is to force the Culture for the test , using _Thread.CurrentThread.CurrentUICulture.
You need to think about reverting it to the previous value.
Alternatively, NUnit provides Attributes to force the culture.

**Comment by SilNak** [comment]
Hi dupdob,

Thank you for the good tip! It is a good workaround.

Basically, I like nFluent for the independence it gives from Unit Test Frameworks (UTF).
      _Above the ones that do not offer the same level of service._
Indeed on an existing sources codes, I do not often have the degree of liberty to switch from one UTF to another.

**_To keep the strength of nFluent, the latter _should keep (My 2po)_, the minimum adherence to them until reducing them a simple test runner._**

**Comment by dupdob** [comment]
Hello
For information I have just created issue #149 to address API/library related needs.

In order to help everyone understand this problem more clearly, can you please elaborate on why you need to check for the content of the error message of an exception? What is the use case here?

**Comment by SilNak** [comment]
Hi,

Simply because some regular Exception raised by .Net does not give enough details.
So your are obliged to lookup for string in the message to make sure it is what you expect.
