### ISSUE TITLE
.WithMessage(...) with partial message

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#147]
Hi there,

Some times error message are composed **_on an invariant pattern_** and **_free message text_** that can vary, as the following:

`Check.ThatCode(() => { throw new ArgumentNullException("MyParam", "How my god!"); }).Throws<ArgumentNullException>().WithMessage("How my god!\nNom du paramètre: MyParam");`

So, to cover this case, it would be interesting to get something like **_WithMessageContains_**:
`Check.ThatCode(() => { throw new ArgumentNullException("MyParam", "How my god!"); }).Throws<ArgumentNullException>().WithMessageContains("How my god!");
`
What's your mind?

**Comment by dupdob** [comment]
I am not confortable to add specific checks for this use case.
I propose to add a way to use the already _string_ related checks for the message, using the following syntax:
`Check.ThatCode(...).Throws<ArgumentNullException>().WhichMessage.Contains("How my god!");`
Would you be confortable with that?

**Comment by SilNak** [comment]
'WhichMessage.Contains' is perfect.

**Comment by dupdob** [comment]
will be included in an upcoming release

**Comment by tvogel8570** [comment]
Was this ever implemented?  I tried to use and it didn't show up in Intellisense.

**Comment by dupdob** [comment]
yes, but with a different, more powerful approach
https://github.com/tpierrain/NFluent/wiki/Check.ThatCode#withmessageexpected
I just realised it was left out of the documentation, so thanks for asking!

**Comment by tvogel8570** [comment]
Thanks, after I included a using NFluent.ApiChecks it appeared in Intellisense and does just what I need.

I really appreciate your efforts to make this capability available, updated and "fluent"
