### ISSUE TITLE
Improve error messages for numerical equality checks

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#153]
Users are often surprised by the fact the following checks fails:
`short Value =1;
Check.That(Value).IsEqualTo(1);
`
Indeed, 1 is an _int_ whereas Value is a _short_. For those cases, the error messages can be made more explicit.
I propose to have a sentence explaining that this is the expected value but **not the expected type**. It will provide improved guidance.

**Comment by SilNak** [comment]
I like the API provide some guidance that way!

**Comment by rhwy** [comment]
Even if it is something that we can expect from the system, maybe we should be more explicit on the behavior and the error message: 

1. if `((short)1).IsEqualTo(1)` means true for most people that's fine, make it work that way, we don't need to be that strict, a natural understanding of the api is far more important.
2. for those that want to make the test not only on value but also on types use another word! something like `((short)1).IsExactMatchForValueAndType(1)` is more explicit and having both will help to avoid confusion.
3. you can link one to other in error messages to help people (ex: "_tested value equals expected value but their type are different, please use IsEqualTo if you only care about the value and not the type instead_")

**Comment by dupdob** [comment]
I think it is the proper approach. Technically this is a breaking change, though.
@tpierrain and @rhwy : confortable with the break? Personally, I am

**Comment by rhwy** [comment]
yep, as I said, this change sounds good for me

**Comment by tpierrain** [comment]
I don't know. I'm still wandering whether or not it's a good thing to introduce this breaking change (may be important for people). I suggest we ask the community through the NFluent newsgroup and see how it goes.

In case we decide to change the existing behavior, I would recommend something like:

       ((short)1).IsEqualTo(1).And.HasSameType();  // the power of idiomatic sameness

What do you think?
