### ISSUE TITLE
Add a way to check for equality using operator== instead of Equals

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#154]
Currently, NFluent checks for equality using _object.Equals(object)_ method. Some users may want to use the _operator==_ instead!

**Comment by dupdob** [comment]
I propose to use _HasSameValueThan_ as in:
`Check.That(mySelf).HasSameValueThan(clone);`

**Comment by SilNak** [comment]
Hi,
Why not IsEqualEqual (.Not.IsEqualEqual) ? This suggests the operator itself...

The question is what could the name for operator != ? .Not.HasSameValueThat() !
If you don't find my suggestion consistent with other naming, on my side, as soon as a detailed comment information that states it is for == operator, It would be ok.

**Comment by MendelMonteiro** [comment]
Do we really need to have an assert that uses the ==operator?  There are two concepts that need to be checked value equality and reference equality.  If a class implements the ==operator to check value equality the Equals method should be doing the same thing.  If they haven't implemented it then calling ReferenceEquals seems more explicit.

If you do go ahead and create the method I would suggest "HasSameValueAs" rather than "HasSameValueThan".

**Comment by dupdob** [comment]
Hello
trigger for this proposal can be found in issue #140.
I share your opinion regarding naming. _HasSameValueAs_ is better.

**Comment by dupdob** [comment]
Coming back to what is the expected behavior of `operator==`, the C# is a bit ambiguous: it is value equality for value types and reference equality for classes. I would assume most developers assume it is value equality. But since you do not share this point of view @MendelMonteiro, I am not so sure

**Comment by SilNak** [comment]
Go ahead for 'HasSameValueAs'! Please include it invoke the operator== in the intellisense.

**Comment by MendelMonteiro** [comment]
I was trying to say that if you overload the ==operator you are not going to do so by checking solely the reference equality.  Therefore, if you want to test an overloaded ==operator you want to test value equality.  In 99% of cases you would also want to override Equals() as you don't want the case where `a == b != a.Equals(b)`.

The only case where this is justifiable is where you for some reason cannot override Equals() - as is the case in issue 140.  However this seems like a really small edge case

**Comment by dupdob** [comment]
My early tests show that it is going to be difficult to implement due to signature issue.
As far as I understand it, I need to use reflection and perform signature resolution 'manually'.
Probably even less fun than it sounds

**Comment by dupdob** [comment]
Reflection is not that bad after all. A bit ugly on the side, but reasonably complex (thanks to the 'static' requirement for equal operators). Need to test my code with covariance now

**Comment by dupdob** [comment]
Covariance is supported. So greenlight for the change. I will also add _HasAValueDifferentFrom_ that will be using `operator!=`.
Note that if no _operator==_ (respectively _operator!=)_ is defined for the considered types, the check will revert to use _IsEqualTo_ logic.

**Comment by dupdob** [comment]
Included in 2.0
