### ISSUE TITLE
.NET Core version of NFluent

### ISSUE THREAD

**Issue by ngm** [tpierrain/NFluent#164]
Hi,

Is there any thoughts of creating a .NET Core version of NFluent?  In particular a netstandard version that can run cross-platform.  NFluent is used extensively in the testing of https://github.com/picklesdoc/pickles, which I am currently porting to .NET Core.

(Apologies if this has been discussed elsewhere, but I could not see any mention of it while searching.)

**Comment by dupdob** [comment]
This was in discussion indeed, but not requested so far. We are keen to make NFluent available on .Net Core. We need to see how much effort it requires.

Cordialement
Cyrille Dupuydauby

**Comment by dupdob** [comment]
Started the effort. Code hase been migrated effortlessly, but not able to build it yet (CS7038: Failed to emit module 'NFluent.Core').

**Comment by dupdob** [comment]
I am open to suggestion. As far as I understand it, CS7038 probably means there was a compilation error that was not properly reported. It can either be some actual code/syntax issue or some internal error... it may be a longer road than anticipated

**Comment by dupdob** [comment]
I am currently rebuilding a project from scratch, adding files one by one (see #165). So far, building Works fine

**Comment by ngm** [comment]
@dupdob I have followed the same approach for porting some projects to .NET Core - creating a new project, and adding files by scratch.  I found this blog post quite helpful: http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/

Let me know if there is anything I can do to help (such as building/running/testing on Ubuntu for example).

**Comment by tpierrain** [comment]
Thanks to both of you. It seems that next release of #nfluent will works under dotnet core.

**Comment by dupdob** [comment]
CS7038 has been fixed. It was due to naming conflict: local variable having the name of a type _(BindingFlags)_ :legal (but ugly) in .Net, not supported with .net core
Next step is T4 generation

**Comment by dupdob** [comment]
Implemented #166 (reorganisation)
Migrated files from NFluent 3.5 to NFluent.Core
Fixed issues with T4 generation
Refactored some tests due to internal namespace changes

**Comment by dupdob** [comment]
Done. Needs to be released

**Comment by tpierrain** [comment]
Cool! Copy that.

Envoyé de mon iPhone
