### ISSUE TITLE
Reorganize project files

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#165]
Folder and namespace structures could benefit from some clean up as they have grown through the years

**Comment by tpierrain** [comment]
+1 ;-)

**Comment by dupdob** [comment]
Here is the proposed target structure. Principles are:
align namespaces are stored into namesake folder. But a namespace can be break down into multiple folders for convenience. I.e: NFluent.Extensibility classes are filed within the extensibility folder. But the 'Checks' folders store classes from the NFluent namespace.
Namespaces
- NFluent: public entry points and associated interfaces, standard checks
- NFluent.Kernel: internal classes used for implementation of the core logic of NFluent
- NFluent.Messages: implementation of message construction logic
- NFluent.Extensibiliy: classes supporting extensions ton NFluent, focusing on helping implementation of custom checks
- NFluent.ApiChecks: checks dedicated to API checking. Currently internal only, until sufficient value is reached

Folders
- namespaces are stored in the folder with same name (e.g.: Kernel)
- all public Checks are stored in the Checks folder
- T4 generated checks are stored in a dedicated folder ('T4')
- Obsolete folder stores obsolete classes

**Comment by tpierrain** [comment]
Like it! The only important thing is to not impact the end-users experience.

**Comment by dupdob** [comment]
Potential impacts:
- some public classes may have unwittingly changed of namespace (unlikely)
- some public classes are no longer public. Rather should never be in the first place (most classes in Kernel namespace)
Target is to have
- no impact for NFluent users
- minimal impact, if any, to NFluent extenders. Changes should be limited to namespace changes (automatically handled by reshape per)
There will be breaking changes for extension using NFluent internals, due to visibility restriction. I propose to evaluate potential rollbacks on visibility on a per request basis.

**Comment by dupdob** [comment]
This proposal has been implemented on my master branch in the NFluent.core project
It will be tested when I'll have migrated tests

**Comment by tpierrain** [comment]
Ok. Let's see if it triggers a 2.0 release (instead of a 1.4)
