### ISSUE TITLE
Add additional Collection/Enumerable checks

### ISSUE THREAD

**Issue by zastrowm** [tpierrain/NFluent#183]
Porting over from `FluentAssertions`, I noticed two useful methods that were missing:

```
Check.That(_collection).ContainsElementAt(3, myExpectedValue);
Check.That(_collection).Contains(item => PredicateThatMustBeTrueForSomeItem(item));
```

Specifically methods for:
 - Checking for an element at a specific index
 - Checking for an element using a predicate

**Comment by dupdob** [comment]
Hello
thanks for reaching out. 
Regarding containselementat, why are you not happy with ?
`Check.That(_collection[3]).IsEqualTo(myExpectedValue);`

**Comment by zastrowm** [comment]
From `FluentAssertions`, it was nice having the index explicitly mentioned in the error message.  It also allows using `IEnumerable` without having to use `ElementAt` (though this is very minor).

**Comment by dupdob** [comment]
Hi @zastrowm 
I am working on your first request. We strongly focus on fluent API for legibility, and I am not confortable with your initial proposal, _ContainsElementAt(index, item)_, as I deem it as not explicit enough.
What do you think of :
`Check.That(_collection).ContainsElementAt(3).Which.IsEqualTo(myExpectedValue)`
One of the benefit of this approach is that it allows for the full set of checks, so if your checking a collection of strings:
`Check.That(_collectionOfStrings).ContainsElementAt(3).Which.StartsWith(myExpectedprefix)`
or
`Check.That(_collectionOfCollection).ContainsElementAt(3).Which.ContainsElementAt(2).Which.IsEqualTo(myExpectedValue)`

**Comment by dupdob** [comment]
Hi
I just pushed an implementation of the predicate based version. Syntax is:
`Check.That(_collection).HasItemThatMatches( (_) => predicate(_))`

Example:
`
IEnumerable<string> randomWords = new List<string> { "yes", "foo", "bar" };
Check.That(randomWords).HasItemThatMatches((_) => _.StartsWith("ye"));
`
The related tests (and code samples) can be found [here](https://github.com/NFluent/NFluent/blob/master/tests/NFluent.Core.Tests/EnumerableRelatedTests.cs#L304)

**Comment by zastrowm** [comment]
Sorry - I forgot to reply to your second response.  The `HasElementThatMatches` looks good.  I also do think that `Check.That(_collection).ContainsElementAt(3).Which` would make a good addition.
