### ISSUE TITLE
IsSameReferenceThan is gramatically incorrect

### ISSUE THREAD

**Issue by cmeeren** [tpierrain/NFluent#190]
One can say "A is the same as B", but not "A is the same than B". [Source here](http://dictionary.cambridge.org/grammar/british-grammar/adjectives/same-similar-identical):

> **Warning:** *The same* is followed by *as*. It is not followed by *that* or *than*.

I suggest deprecating `IsSameReferenceThan` and replacing it with `IsSameReferenceAs` (or perhaps just `IsSameAs` or `Is`).

While I'm at it, I also suggest obsoleting `IsDistinctFrom` and instead using `IsNot...`, corresponding to the chosen name above.

**Comment by dupdob** [comment]
Fixed on Github, to be released as part of V2.0

**Comment by cmeeren** [comment]
Great! Do you know how far off that is?

**Comment by dupdob** [comment]
Should be before end of june.
