### ISSUE TITLE
Add Support for Net 2.0

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#191]
Provide at least partial support for Net 2.0

**Comment by dupdob** [comment]
Done. It will work properly assuming your build chain support extension methods (VS 2008+). Checks related to features not supported by Net.20 are not available.

You may have issues with Check.ThatCode as Action and Func<> are not part of the Net 2.0 framework. NFluent provides similar types, so you can use NFluent.Func<> and NFluent.Action instead.

**Comment by tpierrain** [comment]
Cool! Congrats.
