### ISSUE TITLE
Throws don't catch exception with ThatAsyncCode 

### ISSUE THREAD

**Issue by fpellet** [tpierrain/NFluent#204]
Hello,

I found a bug with Check.ThatAsyncCode. The action is computed before capturing the exceptions.

Example :
`
Check.ThatAsyncCode(() => Task.FromResult(new Exception("Error")))
                 .Throws<Exception>();
`
Result :
The checked code did not raise an exception, whereas it must.
Expected exception type is:
	[System.Exception]
   at NFluent.CodeCheckExtensions.<>c__DisplayClassd'1.<Throws>b__c()
   at NFluent.Extensibility.Checker'2.ExecuteCheck(Action action, String negatedExceptionMessage)
   at NFluent.CodeCheckExtensions.Throws[T](ICodeCheck'1 check)

instead of to succeeding

**Comment by cptjazz** [comment]
``Task.FromResult(..)`` with an Exception object does not do what you think. You should use ``Task.FromException<T>(..)``.

**Comment by fpellet** [comment]
It's simple and stupid example, but the action can call method with unknown implementation.

**Comment by cptjazz** [comment]
@fpellet Your usage of Tasks is not correct. ``Task.FromResult(..)`` does not create a Task in a 'Faulted' state, so it will always succeed, containing the exception object as payload -- but it does never throw. Try wrapping your ``Task.FromResult(new Exception())`` in a try-catch or try awaiting it and see what happens. 
A Task in a 'Faulted' state will only be created by ``Task.FromException<T>(..)``
Please refer to https://msdn.microsoft.com/en-us/library/dn823324(v=vs.110).aspx

**Comment by fpellet** [comment]
Ho sure, sorry. Too quickly. Very bad example :)

```
Check.ThatAsyncCode(() => Execute(5)).Throws<Exception>();

private Task<object> Execute(int i)
{
    if (i == 5)
    {
        throw new Exception(null);
    }
    
    return Task.FromResult<object>(null);
}
```

**Comment by dupdob** [comment]
This test works fine with the latest beta. Do you still have an issue?

**Comment by fpellet** [comment]
1.3.1 => KO
2.0.0-alpha => KO
2.0.0-alpha-44 => OK
2.0.0 => OK

So yes, it's work fine. Sorry, I thought I had already switched to version 2.0.0

**Comment by dupdob** [comment]
Thanks for reporting. I do reproduce the issue with 1.31. I will try to understand when it got fixed, but it will be difficult, as the project files have been reorganized several times since

**Comment by dupdob** [comment]
Investigation over: the issue has been fixed accidentally while refactoring the wrapper for async code.
Original (buggy) code can be seen here: https://github.com/tpierrain/NFluent/blame/00bed97d322d7d63890f2543919404d9f01a6673/NFluent.Core/Kernel/FluentCodeCheck.cs#L224
