### ISSUE TITLE
Add type information in error messages for Enumerable checks

### ISSUE THREAD

**Issue by phoenix-iv** [tpierrain/NFluent#212]
The enumerable checks for Contains, ContainsExactly and IsOnlyMadeOf fail when numeric value types are different but contain the same values.  This is fine, but the error message is confusing because it contains no information about the types in the enumerable.
For example the following code
<pre>
var expected = new int[] { 1, 2 };
var actual = new uint[] { 1, 2 };
Check.That(actual).ContainsExactly(expected);
</pre>
will report
<pre>
Message: NFluent.FluentCheckException : 
The checked enumerable does not contain exactly the expected value(s). 
First difference is at index #0.

The checked enumerable:
	[1, 2] (2 items)
The expected value(s):
	[1, 2] (2 items)
</pre>
which makes looks like the enumerable contains the exact same values, while in reality they have two different types.

**Comment by dupdob** [comment]
This should not happen in V 2.1. I'll reproduce

**Comment by dupdob** [comment]
Hello
This Check succeeds with NFluent 2.1! Can you please upgrade and confirm?
This change has been introduced in 2.1 to improve enumerable comparison, if this is an issue for you, please provide rationale...
