### ISSUE TITLE
Add Check.That(sut).HasSamePublicMembersWithSameValues(otherInstance)

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#214]
When it comes to compare various DTOs, resources/representations it would be handy on my current project to have a 

     Check.That(sut).HasSamePublicMembersWithSameValues(otherInstance)

with same behaviour than the HasFieldsWithSameValues() but to be applied only on public members (i.e. fields and properties).

**Comment by dupdob** [comment]
This is definitely a better offer than the current _HasFields..._ check. By the way, it is worth reminding this was a research topic that accidentally was released in the wild  👎 .
Implementation should be straightforward, my concern is naming related. _HasSamePublicMembersWithSameValues()_ has not much for it, except a record length.
I propose to have a two steps syntax, something like:

_Check.That(sut)._**Has(Fields|Attributes).That.**_IsEqualTo(expected)_

Naming of extraction/scoping to be confirmed

**Comment by dupdob** [comment]
Progress report: here is the proposed syntax:
_Check.That(sut)._**Considering().Public.Fields**_.IsEqualTo(expected)_
