### ISSUE TITLE
Add support for non generic methods IsInstanceOf<> and the like

### ISSUE THREAD

**Issue by tjaskula** [tpierrain/NFluent#218]
Hi,

In some cases it would be nice to have a choice between generic and non generic methods. For example `IsInstanceOf<>` cannot be used in a parametrized unit test when a type you want to assert against is passed as a parameter of the test method.

**Comment by dupdob** [comment]
Interesting suggestion. Can you elaborate a bit on your use case? I prefer to create new  rather than variants.

**Comment by tpierrain** [comment]
@dupdob why do you prefer to create a new rather than variants here? I think we are talking about the same intention here (whether the generic or the non-generic cases).

**Comment by dupdob** [comment]
My comment was general, not specific: I prefer to cover new use cases than adding variants.
My question was just to get understanding of real world use case and use that knowledge to improve the library.
For example, this looks like a 'factory' related test; so there may be an opportunity to have an even better check.

**IsAnInstanceOf** is definitely more about testing implementation than behaviour...

**Comment by dupdob** [comment]
Important: the non generic version is readily available. I just want to be given the opportunity to improve on the proposal.

**Comment by tjaskula** [comment]
This is a simple test that should help to understand the issue:

```
[TestCase(typeof(FondsIdsMappingRepository))]
        [TestCase(typeof(PartsIdsMappingRepository))]
        [TestCase(typeof(SocietesIdsMappingRepository))]
        public void Resolve_correctly_registered_repositories(Type repositoryType)
        {
            var service = Substitute.For<IServiceProvider>();
            var factory = new IdsMappingRepositoryFactory(service);
            service.GetService(typeof(FondsIdsMappingRepository)).Returns(new FondsIdsMappingRepository(null));
            service.GetService(typeof(PartsIdsMappingRepository)).Returns(new PartsIdsMappingRepository(null));
            service.GetService(typeof(SocietesIdsMappingRepository)).Returns(new SocietesIdsMappingRepository(null));
            service.GetService(typeof(FakeIdsRepository)).Returns(null);

            var repository = factory.GetMappingRepository(repositoryType);
            Assert.That(repository.GetType() == repositoryType);
        }
```

Maybe my case is too specific, but it could be useful sometimes

**Comment by dupdob** [comment]
Thanks for taking that much time for your sample. If I am correct, your sample code simply test the MockLibrary.
I guess your actual tests use your own factory, right?
In any case, that's good enought for me. I will push the new check in the next beta.
Proposed name is: Check.That(sut).**InstanceOfType(_Type expectedType_)**

**Comment by rhwy** [comment]
**Is**InstanceOfType(type) instead maybe?

**Comment by dupdob** [comment]
Thanks, typo hre:
Check.That(sut).**IsInstanceOfType(_Type expectedType_)**

**Comment by dupdob** [comment]
Added: 
Check.That(sut).**IsNoInstanceOfType**(Type expectedType)

**Comment by dupdob** [comment]
Added **IsNotInstanceOfType**,**ThrowsType**
