### ISSUE TITLE
InvalidCastException when using Check.ThatCode(...).Not.Throws<T>()

### ISSUE THREAD

**Issue by Amarok79** [tpierrain/NFluent#228]
NFluent 2.2

The following test code causes NFluent to throw an InvalidCastException.

```
public class Foo
{
    public void Throw()
    {
        throw new InvalidOperationException();
    }
}

[Test]
public void TestCase()
{
    Check.ThatCode(() => new Foo().Throw())
        .Not.Throws<ArgumentNullException>();
}
```

The exception message says:
`System.InvalidCastException : Unable to cast object of type 'System.InvalidOperationException' to type 'System.ArgumentNullException'.`

This might be an edge-case, because you usually check for specific exceptions to be thrown or for no exceptions at all. In my test case, I want to ensure that only a single specific exception isn't thrown; other exception types are accepted, even no exception is okay.

**Comment by dupdob** [comment]
Thanks for reporting this. This is clearly a bug. 
Your expectations are correct. 
Quick question: is it a regression due to V2.2?

**Comment by Amarok79** [comment]
Correct, in NFluent 1.3.1 it worked. Starting with 2.0.0, also in 2.1.1 and 2.2.0 it fails.

Thanks for fixing. I considered to create a PR, but I'm still not familiar with your codebase.

**Comment by dupdob** [comment]
I pushed a beta package on myget. I would be grateful if you could try it and confirm it resolves your issue. Details are here: [NFluent Myget feed](https://www.myget.org/feed/dupdobnightly/package/nuget/NFluent)

**Comment by Amarok79** [comment]
Verified. The reported issue is fixed; other test are not broken.

**Comment by dupdob** [comment]
Thanks for the response. I am currently working on 2.3.0 version that will integrate this fix as well as several new features.
