### ISSUE TITLE
Provide Shouldly and FluentAssertion like syntax

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#253]
Shouldly and FluentAssertion both offer extension methods that be used directly on the _sut_, insteat of having a specific method. 
NFluent could offer a similar syntax to ease transition

## Expected Behavior
having 
```csharp
sut.Verify().IsEqualTo(..)
// equivalent to
Check.That(sut).IsEqualTo(...)
```

## Current Behavior
Not supported.

**Comment by dupdob** [comment]
Implemented as an alpha feature in V2.3.2
Keyword is **Verifies** as in
```csharp
2.Verifies().IsEqualTo(2);
```

**Comment by MendelMonteiro** [comment]
Doesn't sound very fluent to me

**Comment by tpierrain** [comment]
What would be the objective of that feature?

**Comment by dupdob** [comment]
Seduce FluentAssertion/Shouldly users. Offering an alternative syntax.
I did this mostly as an experiment

**Comment by dupdob** [comment]
Existing implementation has been remvoved. A gist is provided instead.
