### ISSUE TITLE
HasElementThatMatches does not handle arrays

### ISSUE THREAD

**Issue by nmorbieu** [tpierrain/NFluent#254]
Hello,
Here is a small bug I encountered:

## Expected Behavior
It should work for arrays as it works for List<>

## Current Behavior
It throws a 
System.InvalidOperationException : L'énumération n'a pas commencé. Appelez MoveNext.
   à System.SZArrayHelper.SZGenericArrayEnumerator`1.get_Current()
   à NFluent.EnumerableCheckExtensions.<>c__DisplayClass8_0`1.<HasElementThatMatches>b__0

## Code that reproduce the issue 

```csharp
        [Test]
        public void ShouldHandleArrays()
        {
            IEnumerable<string> randomWords = new [] { "yes", "foo", "bar" };
            Check.That(randomWords).HasElementThatMatches((_) => _.StartsWith("ye"));
        }
```

**Comment by dupdob** [comment]
Thanks for reporting this. Clearly a bug, with a clear faulty line. Need to check while current tests did not report the issue.
Fix will be released in a new beta.
