### ISSUE TITLE
Exception on 'Contains' check in a special case

### ISSUE THREAD

**Issue by lemichael** [tpierrain/NFluent#261]
When a check, whether a string (haystack) contains another string (needle), is unsuccessful and the needle contains a substring in form `{something}`, an exception is thrown while printing a test result. This happens with `ICheck<string>.Contains()` method.

## Expected Behavior
The test result should be printed correctly:
```
The checked string does not contain the expected value(s): "{World}"
The checked string:
	["Hello, {LeMonde}"]
The expected value(s): contains
	["{World}"] (1 item)
```

## Current Behavior
An exception `System.FormatException` is raised:
```
System.FormatException
Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at NFluent.Extensibility.FluentMessage.ToString()
   at NFluent.Kernel.CheckLogic`1.ReportError(FluentMessage fluentMessage)
   at NFluent.StringCheckExtensions.Contains(ICheck`1 check, String[] values)
   at ... (elided)
```
However, it seems to work correctly if haystack contains `{something}` but needle does not.

## Possible Solution
Defensive escaping of needle on output.

## Code that reproduce the issue
```csharp
[Fact]
public void Test() {
      var haystack = "Hello, {LeMonde}";
      var needle = "{World}";
      Check.That(haystack).Contains(needle); // This will intensionally fail
}
```

## Context
This unexpected behavior was discovered during a test of a template engine.

## Your Environment
* Version used: 2.3.1
* Framework version: .NET Framework 4.6.1
* Link to your project: None

Tested on: xUnit 2.4.0 and MSUnit, Visual Studio 2017+Resharper Test Runner

**Comment by dupdob** [comment]
Thanks for the reporting. I confirm I reproduce your issue with the latest beta. This is indeed a bug.
Working on a fix

**Comment by dupdob** [comment]
Fix has been indentified

**Comment by lemichael** [comment]
Thank you for NFluent!
