### ISSUE TITLE
Add sourcelink support

### ISSUE THREAD

**Issue by pmiossec** [tpierrain/NFluent#264]
Please add [sourcelink](https://github.com/dotnet/sourcelink) support in nfluent.

## Expected Behavior

Being able to "Step into" the nfluent code of any version (supporting sourcelink) when debbuging a unit test.
That surely make a lot easier to detect a nfluent bad behavior by its users and report issue...

## Current Behavior

It's impossible to debug nfluent code (except in building it's own version)

**Comment by dupdob** [comment]
If I understand 'sourcelink' correctly, it is available for assemblies that target netcore 2.1+.
For the time being, there is no netcore 2.1 specific distribution of NFluent (but there is **net.standard 2.0 version**).

Corollary:
- Need to add a new netcore 2.1 target to the build process (see #265), which will slow the build process
- Feature will only be available to netcore 2.1.3+ projects

Do you have any actual problem that would help justify this effort?

**Comment by dupdob** [comment]
First attempt fails in appveyor

**Comment by dupdob** [comment]
Second attempt succeeded . Feature is available for Core 2.1+ projects

**Comment by tpierrain** [comment]
This is great. Thanks!

Envoyé de mon iPhone

**Comment by dupdob** [comment]
I would love to have some report regarding its benefits. I have a lot of doubts on this....

**Comment by pmiossec** [comment]
Thanks a lot for the quick and great work, cyrille.

>I would love to have some report regarding its benefits. I have a lot of doubts on this....

That's a feature that all the open source libraries should have because that make debugging and finding bugs a lot easier for developers external to the project.

I opened this issue because I found a bad behaviour in nfluent (in fact a bug that was fixed in the last version that I was not using). As it was the second time I found a strange behavior without being able to debug without building my own version (what I didn't have the time at the moment and could be painful when you're not part of the project) I feel a frustration because the feature was not there...

But indeed, developers should be aware of this feature. I hope this feature will be much more known now that the project is now one of the .Net foundation. Projects using this feature should also inform there users of the feature and how to use it...

So the feature is useful, but not very known ;)

PS: I will have a look but I think that this is possible to add the feature to the netstandard project (that will much more useful for not dotnet core projects)

**Comment by dupdob** [comment]
Thanks for feedback.
First of all you can try it using the latest beta (2.4.0.187 and above) available on [myget](https://www.myget.org/feed/dupdobnightly/package/nuget/NFluent).

I understand your frustration with debugging as one of the objectives/purposes of NFluent is to reduce the reliance to debugging.
If you spot potential bad behaviors, my recommandation is to try and isolate it with a simple test. Then either report it, or try to fix and create a pull request for the fix.

**Comment by dupdob** [comment]
Implementation status update:
- fyi I had to use SourceLink.CommandLine (insteaf of SourceLink.Github) for it to work properly
- therefore I was able to remove the dependency on Net Core 2.1
- I have generalized SourceLink to major Framework version
- therefore, it is available for Netstandard2.0 (tested) and it should work for netstandard 1.6, net 4.5 and net 4.0
