### ISSUE TITLE
Adapting the msbuild config path to Visual Studio

### ISSUE THREAD

**Issue by eOkadas** [tpierrain/NFluent#267]
## Expected Behavior
Building with the provided scripts should not be dependent on Visual Studio edition.

## Current Behavior
Building with the provided scripts is dependent on Visual Studio being installed as **Community** editon, it fails if you are using Professional or enterprise.

## Possible Solution
Adding Condition switches to ```.build\buildlogic.targets```
```xml
    <VsPath Condition="Exists('$(MSBuildProgramFiles32)\Microsoft Visual Studio\2017\Community\')">$(MSBuildProgramFiles32)\Microsoft Visual Studio\2017\Community\</VsPath>
    <VsPath Condition="Exists('$(MSBuildProgramFiles32)\Microsoft Visual Studio\2017\Professional\')">$(MSBuildProgramFiles32)\Microsoft Visual Studio\2017\Professional\</VsPath>
    <VsPath Condition="Exists('$(MSBuildProgramFiles32)\Microsoft Visual Studio\2017\Enterprise\')">$(MSBuildProgramFiles32)\Microsoft Visual Studio\2017\Enterprise\</VsPath>
    <VsPath Condition="'$(VsPath)'==''">false</VsPath>

    <MsTestRunnerPath>$(VsPath)\Common7\IDE\CommonExtensions\Microsoft\TestWindow\</MsTestRunnerPath>
```

## Your Environment
Working on VS Pro

**Comment by dupdob** [comment]
Can you create a Pull Request with that change, so we can credit your work?

**Comment by eOkadas** [comment]
done !

**Comment by dupdob** [comment]
congrats!

**Comment by tpierrain** [comment]
Yes, welcome Etienne, and congrats for this first intervention.
