### ISSUE TITLE
Check.That(TimeSpan.MinValue).IsEqualTo(TimeSpan.MinValue) fails

### ISSUE THREAD

**Issue by fremag** [tpierrain/NFluent#269]
## Expected Behavior
This check should not fail:
```csharp
Check.That(TimeSpan.MinValue).IsEqualTo(TimeSpan.MinValue);
```

## Code that reproduce the issue 

```csharp
....
[Fact]
 public void TimeSpanMinValueTest1()
 {
  Check.That(TimeSpan.MinValue).IsEqualTo(TimeSpan.MinValue); // Ok with NFluent 2.2 but Fails with NFluent 2.3 !
 }
 [Fact]
 public void TimeSpanMinValueTest2()
 {
  Check.That(TimeSpan.MinValue).IsNotEqualTo(TimeSpan.MinValue); // Ok: this always fails as expected
 }
 [Fact]
 public void TimeSpanMinValueTest3()
 {
		 TimeSpan value = TimeSpan.MinValue;
		 Check.That(value == TimeSpan.MinValue).IsTrue();  // ok :)
 }
 [Fact]
 public void TimeSpanMaxValueTest()
 {
		 Check.That(TimeSpan.MaxValue).IsEqualTo(TimeSpan.MaxValue); // Ok :)
 }
...
```

## Context
I upgraded NFluent from 2.2 to 2.4 then some of my unit tests failed.
I checked 2.3 and the check fails too.

## Your Environment
* Version used: 2.4
* Framework version: 4.6.1
* Link to your project: Sorry, I can't give a link. Private corporate project.

Thanks a lot for your work, NFluent is a great tool !

**Comment by dupdob** [comment]
First of all sorry for this issue. 
Thanks for your detailed report
I will look into it ASAP and push a fix on MyGet

**Comment by dupdob** [comment]
hello again
the cause is a loss of precision due to internal conversion to double.
As this is a non trivial fix, I will not be able to fix it today.
I should be able to fix this before Oct 19th.

**Comment by dupdob** [comment]
Correction. I may have found an easy fix. I will perform complementary tests and keep you posted
