### ISSUE TITLE
.WithCustomMessage() extension does not work with dynamic  (.ThatDynamic())

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#280]
The followed line does not compile:

```csharp
Check.WithCustomMessage("I failed here on that stuff").ThatDynamic(dynamicVariable).IsEqualTo(expected);
```

I'm running on .NET 4.7.2

**Comment by dupdob** [comment]
Yes
This has not been implemented. Not sure if it can
For sure this requires work...

**Comment by dupdob** [comment]
Implemented. Identified issue with error messages (see #281).
Will push a beta shortly
