### ISSUE TITLE
What is ContainsExactly alternative ignoring order?

### ISSUE THREAD

**Issue by cico88** [tpierrain/NFluent#282]
How to compare exactly two lists and ignore order, please? The only way I found is to combine Contains and IsOnlyMadeOf, but I don't like it. Thank you for your help.

**Comment by cico88** [comment]
Great, that helped, but how do I use it with "Extracting", 
Check.That(list.Extracting("Property")).IsEquivalentTo ?

**Comment by dupdob** [comment]
That should do the trick

**Comment by cico88** [comment]
I think I got it, Cast was necessary. Otherwise it complains about: 'ICheck<IEnumerable>' does not contain a definition for 'IsEquivalentTo'...

Check.That(list.Extracting("Property").Cast<int>()).IsEquivalentTo

Could you confirm that this is correct usage, please? Thank you again.

**Comment by dupdob** [comment]
Thanks for pointing this out. A cast is indeed needed. 
I'll create an issue to get rid of this.
