### ISSUE TITLE
It would be great to add bool? support for Checks

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#285]
I wish I could use Checks for bool? such as:

     Check.That(umbrellas[0].UsTaxFormW8W9Needed).HasAValue().Which.IsFalse();

This is working nice with int?, long? etc but not for bool? yet.

**Comment by dupdob** [comment]
It has been implemented thanks to PR #273. It will be part of 2.5.0 release.
It is available in current beta.
