### ISSUE TITLE
Allow direct Checks on Collection size

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#291]
It would be nice to have a way to check on the collection {size|length|count} directly from the collection instance.

e.g.: 
```csharp
    Check.That(refData.AgentsByRole.Values).HasSizeWhich.IsStrictlyGreaterThan(42);
```

instead of the existing:
```csharp
    Check.That(refData.AgentsByRole.Values.Count).IsStrictlyGreaterThan(42);
```

**Comment by dupdob** [comment]
I propose ‘WhichSize’ instead is HasSaze

**Comment by yhan** [comment]
> I propose ‘WhichSize’ instead is HasSaze

Maybe WhoseSize is more English :)

**Comment by dupdob** [comment]
indeed
Whose is definitely better

**Comment by dupdob** [comment]
Started working on it. Interestingly, it requires new and improved extension points
