### ISSUE TITLE
New check suggestion for collections

### ISSUE THREAD

**Issue by yhan** [tpierrain/NFluent#293]
May we have this option for collection, instead of 

```CSharp
Check.That(milestones.All(x => HeIsANicePerson(x))).IsTrue();
```

provide this new check

```CSharp
Check.That(milestones).EachElementSatisfies( HeIsANicePerson );
```

**Comment by dupdob** [comment]
Please look into this
https://github.com/tpierrain/NFluent/wiki/Enumerable-types#containsonlyelementsthatmatchpredicate

I think it is what you are looking for!

**Comment by yhan** [comment]
Merci beaucoup :-)
