### ISSUE TITLE
ContainsExactly for IEnumerable<char> fails with NotImplementedException

### ISSUE THREAD

**Issue by KN4CK3R** [tpierrain/NFluent#299]
## Code that reproduce the issue 
```csharp
IEnumerable<char> e1 = "test";
IEnumerable<char> e2 = "test2";

Check.That(e1).ContainsExactly(e2);
```

## Expected Behavior
The check should produce an error message like
```
The checked enumerable does not contain exactly the expected value(s). Elements are missing starting at index #4.
The checked enumerable:
	{'t', 'e', 's', 't'} (4 items)
The expected value(s):
	{'t', 'e', 's', 't', '2'} (5 items)
```

## Current Behavior
The check fails with a NotImplementedException from ValueBlock.cs:80

## Context
The input IEnumerable<char> is the result of a method which converts a list of bytes to chars. In the test I want to check if a given byte array is converted to a specific string (which is implicit converted to IEnumerable<char>).

## Your Environment
* Version used: 2.5.0
* Framework version: Net 4.7.2

**Comment by dupdob** [comment]
Thanks for raising this and providing us a good issue report.
The exception problem fix has been identified. 
There is another problem: NFluent ensures that strings are reported as such and not as enumeration of chars.
Meaning that the actual error message from your example will be
```
The checked string does not contain exactly the expected value(s). Elements are missing starting at index #4.
The checked string:
	["test"]
The expected string:
	["test2"]
```
Are you ok with this, or do you expect an enumeration like reporting?
And if you do, could you please explain your need/rationale for this ?

**Comment by KN4CK3R** [comment]
I'm ok with this but I wouldn't expect it as an user without knowledge. I just call string.ToArray now for my test data so NFluent doesn't know the chars are from a string object. This produces the message I would expect from the method.

**Comment by dupdob** [comment]
Don't get me wrong, I am just trying to figure out what you want to achieve, just making sure we are helping you properly.
Let me try another question: what don't you use **IsEqualTo** ? is there a problem with error reporting?

**Comment by KN4CK3R** [comment]
The test should ensure that the checked `IEnumerable<char>` **ContainsExactly** the elements in the same order as the expected `IEnumerable<char>`. The same check with **IsEqualTo** fails as expected:
```
The checked enumerable is different from the expected string.
The checked enumerable:
	{'t', 'e', 's', 't'} (4 items) of type: [System.Linq.Enumerable+WhereSelectArrayIterator<byte, char>]
The expected string:
	["test"] of type: [string]
```

Maybe I confused you with the string. Here is a new example:
```csharp
public IEnumerable<char> GetData()
{
	yield return 't';
	yield return 'e';
	yield return 's';
	yield return 't';
}

[Fact]
public void TestIEnumerableChar()
{
	IEnumerable<char> expected = new[] { 't', 'e', 's', 't', 't' };

	Check.That(GetData()).ContainsExactly(expected);
}
```
Note: The expected enumerable contains an additional 't' to fail the check.
This example works as intended and displays the message
```
The checked enumerable does not contain exactly the expected value(s). Elements are missing starting at index #4.
The checked enumerable:
	{'t', 'e', 's', 't'} (4 items)
The expected value(s):
	{'t', 'e', 's', 't', 't'} (5 items)
```
It is exhausting to write the expected enumerable like in the example. String to the rescue. It lets me write the characters and is an `IEnumerable<char>`, so lets use it.
```csharp
[Fact]
public void TestIEnumerableChar()
{
	IEnumerable<char> expected = "testt";

	Check.That(GetData()).ContainsExactly(expected);
}
```
Now I get the NotImplementedException and that is not what I'm expecting.

**Comment by dupdob** [comment]
Thank you for your detailed explanation. I think I understand clearly your expectations and you are probably not alone in trying to achieve that.
I will push a beta in the coming hour(s) that will fix the exception  and provide error message similar to the one I provided as an example:
```
The checked enumerable is different from the expected string.
The checked enumerable:
	{'t', 'e', 's', 't'} (4 items) of type: [System.Linq.Enumerable+WhereSelectArrayIterator<byte, char>]
The expected string:
	["test"] of type: [string]
```
This will allow you to write your checks without having to resort to _ToArray()_ or similar tricks.

Proper support will be provided in V.2.6.0 that is planned for next month.

**Comment by dupdob** [comment]
Hello, as explained above, I have just pushed V2.6.0-beta197 which contains the partial fix.
The simplest way to use it in your project is to add it to the nuget configuration in Visual Studio and adding this URL https://www.myget.org/F/dupdobnightly/api/v3/index.json as a source.
You will find alternative methods on the following link:
https://www.myget.org/feed/dupdobnightly/package/nuget/NFluent

Can you please try it and confirm it fixes your issue?

**Comment by KN4CK3R** [comment]
Great, with the beta it is as expected!

```csharp
public IEnumerable<char> GetData()
{
	yield return 't';
	yield return 'e';
	yield return 's';
	yield return 't';
}

[Fact]
public void TestIEnumerableChar()
{
	IEnumerable<char> expected = "testt";

	Check.That(GetData()).ContainsExactly(expected);
}
```

```
The checked enumerable does not contain exactly the expected value(s). Elements are missing starting at index #4.
The checked enumerable:
	{'t', 'e', 's', 't'} (4 items)
The expected value(s):
	{'t', 'e', 's', 't', 't'}
```

**Comment by dupdob** [comment]
Thanks. But I think you should check this without the workaround:
``csharp
[Fact]
public void TestIEnumerableChar()
{
	Check.That(GetData()).ContainsExactly("testt");
}
```

It should work.

**Comment by KN4CK3R** [comment]
Yes, it works.

**Comment by dupdob** [comment]
Once again, many thanks for your inputs and contributions
