### ISSUE TITLE
Restore Intellisense for IsEqualTo

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#314]
Since change #246 has been implemented, IsEqualTo requires an **object**  instance as the expected value, which results in the unavailability of auto-completion. 

## Expected Behavior
Restore support for suggestion features.

## Context
Comment by @MendelMonteiro 
A side effect of this change is that all intellisense is broken when calling IsEqualTo() as it now takes a object instead of T. I personally use IsEqualTo() a lot more often than IsDefaultValue().

**Comment by dupdob** [comment]
I published V 2.6.1 beta 210 with an early fix.
https://www.myget.org/feed/dupdobnightly/package/nuget/NFluent/2.6.1-beta-0210

@MendelMonteiro : could you please test it and confirm if it fixes your issue or not?

**Comment by MendelMonteiro** [comment]
Will have a look on Thursday morning.

**Comment by MendelMonteiro** [comment]
It's definitely better as intellisense suggests better options and I'd welcome the change being released.

However, it's not as good as before as you can mix incompatible types and you won't know until you run the test.

**Comment by dupdob** [comment]
This is a good remark. The short answer is: this is deliberate. But as it deserved a more complete explanations, I just added a page to the wiki to provide the rationale for this choice. 
Please check this [page](../wiki/Design-FAQ).
Your feedback is welcome of course.

**Comment by dupdob** [comment]
implemented in V 2.7.0

**Comment by dupdob** [comment]
It is never too late 😄.
In canonical TDD, does not compile = RED: the test code is written before the code that is to be tested!

**Comment by dupdob** [comment]
The good news is that everyone can use his favorite TDD cycle. But yes, I would; I think I need to do screen cap for this.
Actually, when designing an API, writing the test before the API helps we find the signature I prefer.

**Comment by dupdob** [comment]
The good news is that everyone can use his favorite TDD cycle. But yes, I would; I think I need to do screen cap for this.
Actually, when designing an API, writing the test before the API helps we find the signature I prefer.

**Comment by MendelMonteiro** [comment]
Writing the Act part first yes, but not writing the Assert part before the Act part...
