### ISSUE TITLE
Add IsCloseTo for every numerical types

### ISSUE THREAD

**Issue by dupdob** [tpierrain/NFluent#325]
As of now (V 2.7) , *IsCloseTo* is only available for floating numbers (```float``` and ```double```).
I have received request to add support for ```decimal```. I propose to extend this request to every numerical types.

## Expected Behavior
Support this:
```csharp
Check.That(1m).IsCloseTo(1, 0.2);
Check.That(1).IsCloseTo(0,1);
Check.That(1b).IsCloseTo(0,1);
...
```
## Current Behavior
Previous examples to not compile.

**Comment by eOkadas** [comment]
Hello, je viens d'en avoir besoin sur du ```decimal```. Je peux essayer de faire une PR sur ce point si ça peux aider.

**Comment by eOkadas** [comment]
C'est dans la V3 déjà 😅

**Comment by dupdob** [comment]
oui, j'ai oublié de te prévenir
