### ISSUE TITLE
HasFieldsWithSameValues does not compare a string after it has been compared a first time

### ISSUE THREAD

**Issue by Greybird** [tpierrain/NFluent#331]
## Expected Behavior
All strings, even if already encountered, should be compared

## Current Behavior
After the first check on a string, further occurences are not checked, and do not report differences

## Possible Solution
Seems to be linked to the [ScanField](https://github.com/tpierrain/NFluent/blob/f5bc4040426a3f3ea96dd836c8def1f33420a1aa/code/src/NFluent/Helpers/ReflectionWrapper.cs#L142)/[MapField](https://github.com/tpierrain/NFluent/blob/f5bc4040426a3f3ea96dd836c8def1f33420a1aa/code/src/NFluent/Helpers/ReflectionWrapper.cs#L170) method in ReflectionWrapper

## Code that reproduce the issue 

```csharp
[TestFixture]
public class Test
{

    [Test]
    public void Succeeds()
    {
        var expected = new SomeClass("AAA", "AAA");
        var actual = new SomeClass("AAA", "AAA");

        Check.That(actual).HasFieldsWithSameValues(expected);
    }

    [Test]
    public void Should_Fail()
    {
        var expected = new SomeClass("AAA", "AAA");
        var actual = new SomeClass("AAA", "BBB");

        Check.That(actual).HasFieldsWithSameValues(expected);
    }

    [Test]
    public void Succeeds_2()
    {
        var expected = new TreeClass("AA");
        var actual = new TreeClass("AB");

        Check.That(actual).HasFieldsWithSameValues(expected);
    }

    [Test]
    public void Should_Fail_2()
    {
        var expected = new TreeClass("AA");
        var actual = new TreeClass("AB");

        Check.That(actual).HasFieldsWithSameValues(expected);
    }

    private class TreeClass
    {
        public string Name { get; }
        public TreeClass Child { get; }

        public TreeClass(string s)
        {
            Name = s[..1];
            if (s.Length > 1)
            {
                Child = new TreeClass(s[1..]);
            }
        }
    }

    private class SomeClass
    {
        public string A { get; }
        public string B { get; }

        public SomeClass(string a, string b)
        {
            A = a;
            B = b;
        }
    }
}
```

## Context
We would just expect all fields to be considered for evaluation

## Your Environment

* Version used: 2.7.0 (bug seems to have been introduced in 2.2.0)
* Framework version: net core 5.0
* Link to your project:

**Comment by dupdob** [comment]
thanks for this detailed report.
I have reproduced the issue with the latest version. Will work on a fix soon.

**Comment by dupdob** [comment]
The problem is linked to https://github.com/tpierrain/NFluent/blob/f5bc4040426a3f3ea96dd836c8def1f33420a1aa/code/src/NFluent/Helpers/ReflectionWrapper.cs#L178
This should happen BEFORE testing for recursion.
I am analysing the impact of the change before providing a fix in beta.

**Comment by dupdob** [comment]
I published a new beta which fixes this issue. You can get it on [myget](https://www.myget.org/feed/dupdobnightly/package/nuget/NFluent/3.0.0-beta-0223).

**Comment by Greybird** [comment]
> I published a new beta which fixes this issue. You can get it on [myget](https://www.myget.org/feed/dupdobnightly/package/nuget/NFluent/3.0.0-beta-0223).

I can confirm that the problem is indeed solved by this version.
Thanks

**Comment by dupdob** [comment]
I just published a beta 2.7.1 on Nuget. Could please test it and confirm it is ok for you ?
I will promote it to stable in a few days.

**Comment by Greybird** [comment]
Hi @dupdob , I can confirm this version, AFAICT, is working as expected (most notably, some tests are now to be fixed and they all exhibit the string comparison issue reported).

Thanks for your diligence in providing a fix!

**Comment by dupdob** [comment]
Thanks for your feedback. And thank you for opening this issue in the first place!
Kudos for providing simple code for reprodcution.
