### ISSUE TITLE
IsZero / IsNotZero for doubles should compare to zero, or specify a tolerance

### ISSUE THREAD

**Issue by bacar** [tpierrain/NFluent#333]
Comparing small doubles to zero with IsZero / IsNotZero should compare exactly to zero.

## Expected Behavior

            Check.That(1E-29).IsZero(); // should not succeed! (but does in v2.7.1)
            Check.That(1E-29).IsNotZero(); // should not fail! (but does in v2.7.1)

It behaves as expected for 1E-28. (See https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/decimal-data-type)

## Possible Solution

If the intent is to compare with a tolerance, it would be useful if the name and/or doc comments reflected that ideally with controllable tolerance like `IsCloseTo`, e.g. `Check.That(smallDouble).IsCloseToZero(within: myTolerance)`.

It is arguably a reasonable comparison to zero for most unit test cases, but it can be a surprise if you're familiar with `IsCloseTo` (as this leads you to expect tolerant comparisons to allow specifying a tolerance). As a minimum, it is worth clarifying in the doc comments, and directing people to use `IsEqualTo(0)` if they want exact equality?

## Context

See https://github.com/tpierrain/NFluent/issues/286

Hit this issue with an older version (2.4.0) that would compare -0.5d to 0.5d as IsZero.
This has been fixed in a later version by converting the double to a decimal instead of an int, but this still has the limitations outlined above.

## Your Environment

* Version used: 2.7.1

**Comment by dupdob** [comment]
thanks for reporting this with such precision.
This is an issue and not deliberate. Will fix.

**Comment by dupdob** [comment]
I have reproduced and fixed it. Is it a blocking issue for you, or can it wait until the next maintenance release?

**Comment by bacar** [comment]
Not blocking at all. Thanks for your concern!

**Comment by dupdob** [comment]
fixed in V 2.7.2
