### ISSUE TITLE
FormatException in Verifies when test fail

### ISSUE THREAD

**Issue by Roxeez** [tpierrain/NFluent#340]
**Bug Type**
Please pick one:
- [ ] a check failed to detect an error (false negative), i.e. a test is green while it should be red.
- [ ] a check raised un existing error (false positive), i.e a test is red while it should be green.
- [ ] an error message is invalid/incomplete (please provide samples)
- [x] a ran into an exception.
- [ ] other.

**Describe the bug**
I'm getting this exception when my test fail (in Verifies scope)
```
System.FormatException
Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.Text.StringBuilder.AppendFormat(String format, Object arg0, Object arg1)
   at NFluent.Extensibility.FluentMessage.ToString()
   at NFluent.Kernel.CheckLogic`1.EndCheck()
   at NFluent.CheckMember`2.Verifies(Action`1 func)
```

```csharp
Check.That(result).IsInstanceOf<OkObjectResult>()
    .Which
    .WhichMember(x => x.Value)
    .Verifies(x =>
    {
        x.IsNull();
    });
```

**To Reproduce**
```csharp
public class MyEntity
{
    
}

public class MyExample
{
    public object Value { get; init; }
}

var value = new MyExample
{
    Value = new List<MyEntity>()
};

// Assert
Check.That(value).IsInstanceOf<MyExample>()
    .Which
    .WhichMember(x => x.Value)
    .Verifies(x =>
    {
        x.IsNull();
    });
```

**Expected behavior**
I expected it toshow me explicitly what's the problem instead of a FormatException

**Desktop (please complete the following information):**
- NFluent version: 3.0.1.352
- Net Version: .NET 7
- IDE: Rider 2023.1.4

**Comment by dupdob** [comment]
hi
thanks for reporting this. I have reproduced and fixed this issue. I will be releasing a fix in the coming days

**Comment by dupdob** [comment]
Hi
I did publish V3.0.2.327-beta that contains the fix. Could you please test it and report ? if the problem is fixed, I will publish an official release.

**Comment by Roxeez** [comment]
Yes looks like it's fixed !
