### ISSUE TITLE
Equality comparisons are incorrect for double.NegativeInfinity and double.PositiveInfinity

### ISSUE THREAD

**Issue by bacar** [tpierrain/NFluent#341]
**Bug Type**
Please pick one:
- [ ] a check failed to detect an error (false negative), i.e. a test is green while it should be red.
- [X] a check raised un existing error (false positive), i.e a test is red while it should be green.
- [ ] an error message is invalid/incomplete (please provide samples)
- [ ] a ran into an exception.
- [ ] other.

**Describe the bug**

Equality comparisons are incorrect for `double.NegativeInfinity` and `double.PositiveInfinity`.

**To Reproduce**

        public static IEnumerable<double> DoubleTestCases = new[]
        {
            -1d,
            // double.NaN,
            double.NegativeInfinity,
            double.PositiveInfinity,
            double.Epsilon,
            double.MinValue,
            double.MaxValue,
        };
        
        [TestCaseSource(nameof(DoubleTestCases))]
        public void Check_Double_Equals(double a) => Check.That(a.Equals(a)).IsTrue();
        
        [TestCaseSource(nameof(DoubleTestCases))]
        public void Check_Double_Is(double a) => Check.That(a).Is(a);
        
        [TestCaseSource(nameof(DoubleTestCases))]
        public void Check_Double_IsEqualTo(double a) => Check.That(a).IsEqualTo(a);

**Expected behavior**

All test cases should pass for all special values of double (except perhaps `NaN`, but see note), including + and - infinity.

`Check_Double_Equals` passes for all cases - the other tests ought to pass for all the cases that compare equal with `.Equals` (or `==` -- not shown here).

Arguably should be true for `NaN` as well, which also passes `.Equals` (but not `==`).

**Screenshots**

![image](https://github.com/tpierrain/NFluent/assets/3057510/48e6a1d5-e789-4fd9-8cfa-2a1e016bf879)

**Desktop (please complete the following information):**
- NFluent version: 3.0.1.352
- Net Version: Net Fwmk 4.8
- IDE: Rider 2023.2.3

**Comment by dupdob** [comment]
thanks for reporting this.
I have a fix ready. Will release in coming days.

for `Nan` you have a `IsNan`check.

**Comment by bacar** [comment]
Superb, thanks. 
`IsNan` definitely useful though sometimes you just want to compare equality/equivalence (e.g. a parameterised test with parameterized expectation).

**Comment by bacar** [comment]
Anything I can do to help get a release out? Thanks.

**Comment by dupdob** [comment]
nah
Sorry, was sick last week so things have been delayed.

Just published V3.0.2 with this fix as well as #340. It should be available soon

**Comment by bacar** [comment]
Brilliant, thanks - this fixes things for +/- infinity.
I still have some issues with NaN - have raised #342
