### ISSUE TITLE
Two equivalent LinkedLists with different order are seen as equal

### ISSUE THREAD

**Issue by GTechene** [tpierrain/NFluent#344]
**Bug Type**
A check failed to detect an error (false negative), i.e. a test is green while it should be red.

**Describe the bug**
When checking two equivalent LinkedLists (= same values but not same order), the IsEqualTo check passes while it should not.
IsEquivalent works fine though.

**To Reproduce**

Code using NUnit :

```csharp
[Test]
public void Should_not_be_equal_when_order_is_different()
{
    Check.That(new LinkedList<int>([3, 1])).IsEquivalentTo(new LinkedList<int>([1, 3]));
    Check.That(new LinkedList<int>([3, 1])).IsNotEqualTo(new LinkedList<int>([1, 3]));
}
```

**Expected behavior**

Test should be green here. Two equivalent LinkedLists (i.e. same values but not in the same order) should not be seen as being equal.

**Desktop (please complete the following information):**
- NFluent version: 3.0.3
- Net Version: .Net 8
- IDE: VS 2022 (17.9.3)

**Additional context**
- Problem is probably located here : https://github.com/tpierrain/NFluent/blob/master/code/src/NFluent/Helpers/DifferenceFinders.cs#L365 either at this line or in the [IsAList()](https://github.com/tpierrain/NFluent/blob/master/code/src/NFluent/Extensions/TypeExtensions.cs#L76) extension method (LinkedList does not implement IList, hence the probable root cause).

**Comment by dupdob** [comment]
Just published V3.0.4 which should fix this issue
