### ISSUE TITLE
Add more methods on the IFluentAssertion<numbers> 

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#36]
e.g.:
-   IsNegative
-   IsNaN
-   IsInfinite
-   IsGreaterThan
-   IsLessThan
-   IsGreaterThanOrEqualTo
-   IsLessThanOrEqualTo
-   IsNotPositive
-   IsNotNegative

And add also all the IFluent<IComparable> methods.

Question: are #30 and #31 issues prerequisites?

**Comment by dupdob** [comment]
Done
