### ISSUE TITLE
Add more methods on the IFluentAssertion<IEnumerable> 

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#38]
To be arbitrated with the new proposition of chainable assertions (#39).

e.g.:
-   IsSubsetOf 
-   IsSortedAccordingTo(comparer)
-   HasSameSizeAs
-   IsNotEmpty
-   DoesNotContainNull
-   DoesNotHaveDuplicates
-   ContainsNull
-   IsNullOrEmpty

**Comment by dupdob** [comment]
Added
ContainsNoNullEntry
ContainsNoDuplicate

**Comment by dupdob** [comment]
Added IsSubsetOf
