### ISSUE TITLE
Improves the build script

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#48]
So that it:
1. Has two modes: a 'Continuous build' one and a 'Release' one
1. Tags the version for a release build version
1. Automatically increments the patch version AFTER a build + commit it (whatever the build mode)

**Comment by dupdob** [comment]
Build scripts  now support multiple build streams: CI, nightly, alpha, RC and release
Version tagging is done by appveyor
Culture related unit tests are not run yet
