### ISSUE TITLE
Provide a showcase/sandbox/demo solution to show NFluent in action with various tests runners

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#7]
via a dedicated sample project like Joel did with FEST assert? 
https://github.com/joel-costigliola/fest-examples/tree/master/src/test/java/org/fest/assertions/examples

Very useful to illustrate the usage of the lib to every new users.

Runners may be xunit, nunit and Specflow for instance.

**Comment by dupdob** [comment]
This remains a good idea, but it has been opened for 6 years. It's time to accept it will not happen
