### ISSUE TITLE
Adds a NFluent Visual Studio plugin to improve the .NET TDD experience

### ISSUE THREAD

**Issue by tpierrain** [tpierrain/NFluent#80]
This (R#?) plugin should be able to support the .NET TDD experience helped with dynamics (see. post and comments here for full description: http://www.codedistillers.com/rui/2013/12/23/dynamic-tdd/#comments)

**Comment by dupdob** [comment]
I suggest we close this issue.

**Comment by dupdob** [comment]
Closed after discussing with @tpierrain
