### ISSUE TITLE
IsNotNull and dynamic

### ISSUE THREAD

**Issue by chouteau** [tpierrain/NFluent#85]
If I have a type like

class Command
{
     dynamic Subject {get; set;}
}

When I test if Subject property is not null 

var cmd = new Command();
Check.That(cmd.Subject).IsNotNull();

I have an exception : 'object' does not contain a definition for 'IsNotNull'

how to make good test for it ?

**Comment by SilNak** [comment]
Hi Folks,

Got the same issue, it would be fine to get a way nFluent to work with dynamics!
I faced the same worry, when you to write a 'generic' test when the type of the object tested can vary, the error return is : 
`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'object' ne contient pas de définition pour 'WhichResult'` for instance.

Is there something planned for that ?

Regs

**Comment by dupdob** [comment]
HI @SilNak,
To this day, nothing has been actively planned regarding _dynamics_. Foremost problem is that those are not compatible with extension methods, forcing a specific redesign.
This also implies that all checks have to be reimplemented.

Finally, I am not sure what is the relevance of existing checks for _dynamics_. We need requirements/needs

**Comment by Ouarzy** [comment]
Hey guyz.

Just go through the same issue. We heavily use Dapper on our last project, which lead us to use dynamic, especially in integration tests.

The error with IsEqualTo is a problem. Worse, the use of Equals will not fail and appear as a success (I know it should not be used, but still confusing for beginners).

I think an ideal solution could be to display an error when an attempt to use a dynamic is done. Then you can force the end user to cast the input (then it becomes compatible with NFluent again).
Not sure how it can be done though, maybe Roslyn can help here.

Another solution could be the suggestion of using Check.ThatDynamic(), but it would probably require more change internaly.

I'll be glad to propose some PR to help with this issue if you'd like to.

**Comment by dupdob** [comment]
As far as I know, no fix is planned regarding dynamics and extension methods in .Net.
Which means we have to options: adding (1) Check.ThatDynamic(...) or (2) a specialized Check.That(dynamic sut).
(1) means that people need to think about picking the right entry point, (2) means R# (and maybe Intellisense) will pick Check.That(dynamic _sut)_ whenever _sut_ type is not known at editing time, which is painful from an autocompletion perspective.
We had the same issue with functor, which led to the creation of Check.ThatCode(...)

I will look into (1) and report

**Comment by dupdob** [comment]
Ok, spike done: Check.ThatDynamic(dynamic sut) works. It comes with a lot of design restrictions, but we can make it work. That being said, what kind of checks do we need for dynamic types?
IsNull
IsEqualTo
IsSameReferenceAs
Verify (predicate)
?

**Comment by Ouarzy** [comment]
At least it would cover all my use cases, can't think to something else so far.

**Comment by dupdob** [comment]
The latest nightly build supports isnotnull for Dynamics. 
I will add the others asap

Boolean logic (Not, And) is not supported yet, as it has to be implemented specifically

**Comment by Ouarzy** [comment]
Thx a lot!

**Comment by dupdob** [comment]
Hello
quick update: I just added IsEqualTo and IsSameReferenceAs. I can't do Verify(predicate) as you can't use predicate on dynamic. I will push current version, so the next 'nightly' due this wednesday will contain it.
This mean I will work on adding boolean logic and see if it can be done.
Have you tried the beta version?

**Comment by dupdob** [comment]
Fully available in beta
